runtime: python313
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

beta_settings:
  cloud_sql_instances: "tutaina-43001:us-central1:fastapi-db"

env_variables:
  HOLA_MUNDO: 'hola_mundo'
  DB_HOST: '/cloudsql/tutaina-43001:us-central1:fastapi-db'
  DB_NAME: 'students'
  DB_USER: 'postgres'
  DB_PASSWORD: '123456789angiedaniela'
  
